### ISSUE TITLE
Failed to login.

### ISSUE THREAD

**Issue by Josofia** [DimensionDev/firefly.mask.social#1999]
## Description
Load failed
## Extra Information
- Version: 5.6.0
- Environment: production
- Commit Hash: ed0df37
- UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1
- Timestamp: 2024-07-26T02:00:54.358Z

**Comment by guanbinrui** [comment]
Hi @Josofia, sorry for the inconvenience. It looks like a network error occurred on your device. Are you trying to log in to Farcaster with the `Reconnect with Firefly (FREE)` button?

**Comment by gamez528** [comment]
Please get warpcast installed on your mobile device before connnecting

**Comment by guanbinrui** [comment]
I'm closing this issue. Please reopen it if any new information or problems arise. Thank you!
