### ISSUE TITLE
Variable "$request" got invalid value "" at "request.url"; Expected type "URI". Invalid url 

### ISSUE THREAD

**Issue by ChinaYangKun** [DimensionDev/firefly.mask.social#2448]
## Description
Error: Variable "$request" got invalid value "" at "request.url"; Expected type "URI". Invalid url : {"response":{"errors":[{"message":"Variable \"$request\" got invalid value \"\" at \"request.url\"; Expected type \"URI\". Invalid url ","locations":[{"line":1,"column":26}],"extensions":{"code":"BAD_USER_INPUT","stacktrace":["Error: Invalid url ","    at URI.validate (/usr/src/app/packages/custom-types-shared/lib/uri.type.js:26:19)","    at new BaseType (/usr/src/app/packages/custom-types-shared/lib/base-types/base-type.js:9:14)","    at new StringType (/usr/src/app/packages/custom-types-shared/lib/base-types/string.type.js:10:9)","    at new URI (/usr/src/app/packages/custom-types-shared/lib/uri.type.js:14:9)","    at GraphQLScalarType.parseValue (/usr/src/app/packages/api-lens/lib/shared/types/scalars/uri.js:19:16)","    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:151:26)","    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:49:14)","    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:117:34)","    at coerceInputValueImpl (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:49:14)","    at coerceInputValue (/usr/src/app/node_modules/graphql/utilities/coerceInputValue.js:32:10)","    at coerceVariableValues (/usr/src/app/node_modules/graphql/execution/values.js:132:69)","    at getVariableValues (/usr/src/app/node_modules/graphql/execution/values.js:45:21)","    at buildExecutionContext (/usr/src/app/node_modules/graphql/execution/execute.js:280:63)","    at execute (/usr/src/app/node_modules/graphql/execution/execute.js:116:22)","    at execute (/usr/src/app/node_modules/dd-trace/packages/datadog-instrumentations/src/graphql.js:151:20)","    at executeIncrementally (/usr/src/app/node_modules/@apollo/server/dist/cjs/incrementalDeliveryPolyfill.js:47:34)"]}}],"status":400,"headers":{}},"request":{"query":"mutation SignFrameAction($request: FrameLensManagerEIP712Request!) {\n  result: signFrameAction(request: $request) {\n    ...FrameLensManagerSignatureResult\n  }\n}\n\nfragment CreateFrameEIP712TypedData on CreateFrameEIP712TypedData {\n  types {\n    FrameData {\n      name\n      type\n    }\n  }\n  domain {\n    ...EIP712TypedDataDomain\n  }\n  value {\n    specVersion\n    url\n    buttonIndex\n    profileId\n    pubId\n    inputText\n    state\n    actionResponse\n    deadline\n  }\n}\n\nfragment FrameLensManagerSignatureResult on FrameLensManagerSignatureResult {\n  signedTypedData {\n    ...CreateFrameEIP712TypedData\n  }\n  signature\n}\n\nfragment EIP712TypedDataDomain on EIP712TypedDataDomain {\n  name\n  chainId\n  version\n  verifyingContract\n}","variables":{"request":{"actionResponse":"","buttonIndex":2,"inputText":"","profileId":"0x06dd22","pubId":"0x049b19-0x1a-DA-02193cc9","specVersion":"1.0.0","state":"","url":""}}}}
    at I (https://firefly-staging.mask.social/_next/static/chunks/2637-ba5d29225eacb2b3.js:10835:40085)
## Extra Information
- Version: 6.1.0
- Environment: production
- Commit Hash: 167daec
- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
- Timestamp: 2024-08-29T14:47:07.828Z

**Comment by dudu0506** [comment]
https://github.com/DimensionDev/firefly.mask.social/pull/2451
